name: aic-ftml-gpu
channels:
  - pytorch
  - nvidia  # CUDA support
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # Core ML/AI frameworks with CUDA support
  - pytorch>=2.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Or =12.1 for newer CUDA

  # CUDA toolkit
  - cudatoolkit

  # Computer Vision & Video Processing
  - opencv
  - pillow>=10.0

  # Scientific Computing
  - numpy>=1.24
  - scipy>=1.11.0
  - pandas>=2.0
  - scikit-learn>=1.4
  - pyarrow

  # FAISS with GPU support
  - faiss-gpu

  # Utilities
  - tqdm>=4.66
  - pyyaml>=6.0
  - joblib>=1.3

  # Development tools
  - jupyter
  - ipython

  # Pip dependencies
  - pip
  - pip:
    - open_clip_torch>=2.24.0
    - rank_bm25>=0.2.2
    - lightgbm==4.5.0
    - decord>=0.6.0
    - fiftyone

# Environment variables
variables:
  PYTHONPATH: $CONDA_PREFIX/lib/python3.9/site-packages:$PWD
  CUDA_VISIBLE_DEVICES: "0"  # Use first GPU by default
