name: aic-ftml
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # Core ML/AI frameworks
  - pytorch>=2.1
  - torchvision
  - torchaudio
  - cpuonly  # Remove this line if you want GPU support

  # Computer Vision & Video Processing
  - opencv
  - pillow>=10.0

  # Scientific Computing
  - numpy>=1.24
  - scipy>=1.11.0
  - pandas>=2.0
  - scikit-learn>=1.4
  - pyarrow  # Parquet engine for pandas

  # FAISS for similarity search
  - faiss-cpu  # Use faiss-gpu if you have CUDA

  # Utilities
  - tqdm>=4.66
  - pyyaml>=6.0
  - joblib>=1.3

  # Development tools
  - jupyter
  - ipython

  # Pip dependencies (not available through conda)
  - pip
  - pip:
    - open-clip-torch>=2.24.0
    - rank_bm25>=0.2.2
    - lightgbm==4.5.0
    - decord>=0.6.0
    - fiftyone  # For visualization (optional)

# Environment variables
variables:
  PYTHONPATH: $CONDA_PREFIX/lib/python3.9/site-packages:$PWD
