[tool.ruff]
line-length = 120
target-version = "py39"
exclude = [
    "artifacts",
    "logs",
    "submissions",
    "temp",
    "__pycache__",
]

# Lint rules: pyflakes/pycodestyle + useful extras
lint.select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "PL",  # pylint (subset)
    "RUF", # ruff-specific rules
]

[tool.ruff.lint.isort]
known-first-party = ["src", "scripts", "eval", "plugins"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
skip-magic-trailing-comma = false

